# Generated by Django 3.1.2 on 2020-12-09 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_exchange', '0021_auto_20201129_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='luggage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2020)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
